### ISSUE TITLE
This device is considered as OFFLINE by Zigbee2Mqtt

### ISSUE THREAD

**Issue by trekker25** [yllibed/Zigbee2MqttAssistant#69] opened 2019-10-09 11:33 UTC
All my routers show the message in the title "OFFLINE" 

lamp_moestuin_buiten
Zigbee Id is 0x001788010434cb9c.
Address on Zigbee Network is 0x70CD.
Link quality is 148/255.
Model is LTW010 by Philips.
Hardware version is 1.
This device type is Router

So they have linkquality and can also be reached using Hass.

Other i also have, the Map function looks great, but for some reason all objects keep on moving!?

**Comment by carldebilly** [comment] 2019-10-09 13:46
Duplicate of #15

It's a known problem which should be fixed in the next version of Z2M

**Closed by carldebilly** 2019-10-09 13:46 UTC
