### ISSUE TITLE
OTA update command

### ISSUE THREAD

**Issue by remb0** [yllibed/Zigbee2MqttAssistant#197] opened 2020-02-28 11:45 UTC
**Is your feature request related to a problem? Please describe.**
feature request

**Describe the solution you'd like**
When an update is available it would be nice to click on a update update to send the update command.

**Additional context**
is also would be nice to see not only that an update is available but also which version. so we can check changelog of the device firmware update.

**Comment by CodeFinder2** [comment] 2020-02-28 12:52
Duplicate of #184 ...

**Comment by carldebilly** [comment] 2020-02-29 12:46
Have been implemented by @magpern in pr #184 
Definitely a duplicated.  Thanks for asking!

**Closed by carldebilly** 2020-02-29 12:46 UTC
Labels: enhancement
