### ISSUE TITLE
[BUG] non existing device is listed

### ISSUE THREAD

**Issue by CodeFinder2** [yllibed/Zigbee2MqttAssistant#170] opened 2020-01-22 23:18 UTC
# Describe the bug
There's a device (that I do not have anymore) which is listed in Z2MA but its neither online nor listed it any of Z2M's config files (devices.yaml, database.db). So, IMHO, Z2M doesn't know the device anymore. I've also reset Z2MA without luck. Note that force deleting the device fails in Z2M due to 'device not known' (makes sense).

Even after restarting Z2M and Z2MA, the device does not go away?! 🙈

I think the following log doesn't really belong to the bug but rather to my delete operations (see my other bug #141). 

## Pertinent logs
```text
Log
Starting Zigbee2MqttAssistant v0.3.133+Branch.master.Sha.f490bd70a0401bc6d96a4d02d5f9022a43bb5e9e...
Hosting environment: Production
Content root path: /app
Now listening on: http://[::]:80
Application started. Press Ctrl+C to shut down.
fail: Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware[1]
      An unhandled exception has occurred while executing the request.
System.InvalidOperationException: Another remove in progress for this device.
   at Zigbee2MqttAssistant.Services.MqttConnectionService.RemoveDeviceAndWait(String deviceFriendlyName, Boolean forceRemove) in d:\a\1\s\Zigbee2MqttAssistant\Services\MqttConnectionService.cs:line 666
   at Zigbee2MqttAssistant.Services.BrigeOperationService.RemoveDeviceById(String deviceId, Boolean forceRemove) in d:\a\1\s\Zigbee2MqttAssistant\Services\BrigeOperationService.cs:line 27
   at Zigbee2MqttAssistant.Controllers.HomeController.RemoveDevice(String id, Boolean forceRemove) in d:\a\1\s\Zigbee2MqttAssistant\Controllers\HomeController.cs:line 131
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResourceFilter>g__Awaited|24_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResourceExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.InvokeFilterPipelineAsync()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware.<Invoke>g__Awaited|6_0(ExceptionHandlerMiddleware middleware, HttpContext context, Task task)
```

**Comment by CodeFinder2** [comment] 2020-01-25 01:57
Interesting: suddenly, the device is gone (it's the one I tried to delete in #141). Surprisingly, also all fantom devices listet in [my comment here](https://github.com/yllibed/Zigbee2MqttAssistant/issues/130#issuecomment-577437543) are gone, too?!

The only thing I could imagine that may have caused this is rebooting my entire host (thus, including all Docker containers). Does this make sense to you, @carldebilly? 🙈

(Previously, I just restarted the Hassio addons Z2M & Z2MA using the "RESTART" button in the Hass.io > Dashboard tab.)

**Comment by a7ypically** [comment] 2020-01-28 13:36
I have the same issue.
Can't delete a device which does not exist anymore.

**Comment by brendanmullan** [comment] 2020-02-02 15:25
I also get an error when trying to delete devices that don't exist anymore. Is this related?

```
Error.
An error occurred while processing your request.
Request ID: |44fa4f25-49fec1530fdb6957.

Development Mode
Swapping to Development environment will display more detailed information about the error that occurred.

The Development environment shouldn't be enabled for deployed applications. It can result in displaying sensitive information from exceptions to end users. For local debugging, enable the Development environment by setting the ASPNETCORE_ENVIRONMENT environment variable to Development and restarting the app.
```

**Comment by ademobile** [comment] 2020-02-06 22:12
Not sure if what I have is related, I have a ghost called bridge/log. When I tap on it, I get a page that does not format correctly and you cannot do anything when you click on links. See screen grabs

![92937A81-7E81-4636-9DC0-C5A958391301](https://user-images.githubusercontent.com/25222110/73983170-b5c27f00-492d-11ea-9141-d1d7d043dbdf.jpeg)
![F7E65899-16BA-4FD1-85BF-3AA0DEFD6955](https://user-images.githubusercontent.com/25222110/73983175-b8bd6f80-492d-11ea-9714-0563966c0002.jpeg)
![A24F9597-B6E1-447E-AFB3-5B1EC92C1251](https://user-images.githubusercontent.com/25222110/73983177-b9ee9c80-492d-11ea-9d3a-964683dfcec0.jpeg)

**Comment by CodeFinder2** [comment] 2020-02-06 23:55
@ademobile just realized to have that bug as well.

**Comment by carldebilly** [comment] 2020-02-09 15:14
Yes I know... it's something I did on the `dev` branch.  Thanks for reporting.  Should be fixed soon.

**Comment by carldebilly** [comment] 2020-02-10 00:21
Should be fixed in version `0.3.137`

**Closed by carldebilly** 2020-02-10 00:21 UTC
Labels: bug

**Comment by CodeFinder2** [comment] 2020-02-11 09:09
Thanks! The 'bridge/log' device is gone, great! My other device that this issue was referred to is also gone but probably / rather due to https://github.com/yllibed/Zigbee2MqttAssistant/issues/182#issuecomment-584521400 (but I don't know for sure). 🙈

**Comment by carldebilly** [comment] 2020-02-11 14:38
Yes I have this one too on my installation (#182) I'll need to check it.  I think the problem is coming from Z2M... I'll try to find time later this week to investigate the problem.

I suspect is happening after the rename of a device, it seems to be duplicated on the MQTT broker.
