### ISSUE TITLE
Feature Request: Logs page, with extra features 

### ISSUE THREAD

**Issue by ellnic** [yllibed/Zigbee2MqttAssistant#237] opened 2020-03-29 20:25 UTC
Hello :-)

Thank you for all your work on this project. I’ve not long been using Z2M, and Z2MA has made my transition from DeCONZ to Z2M much easier 👍 

I wonder if it would be possible to implement a logs page with some additional features? At the moment, I find myself having to hunt quite a bit in the supervisor logs section for Z2M, and the logs only go back so far. I am guessing this is a limitation of the hass.io add-ons as most seem to be similarly designed. I also noticed that there seems to be an issue when using Ctrl-F to try and quickly find something e.g. ‘firmware’, you are unable to search the log text. 

Would it be possible to add a better logs page to Z2MA? Something that can search, filter and go back further? Having this, and having it under one add-on means less clicks to move to and from Z2MA and the logs to find that all important line, and the extras would make certain operations much easier to accomplish. 

Thanks. :-)

**Comment by carldebilly** [comment] 2020-03-31 13:28
You're totally right!  It's a duplicate of #36 and #121.

**Closed by carldebilly** 2020-03-31 13:28 UTC
Labels: enhancement

**Comment by ellnic** [comment] 2020-03-31 14:34
Wow, my apologies for sucking so badly at searching! Glad to know it's on the cards :) Thanks
