### ISSUE TITLE
[BUG] Error processing MQTT message on topic 'zigbee2mqtt/bridge/ota_update/update'

### ISSUE THREAD

**Issue by carldebilly** [yllibed/Zigbee2MqttAssistant#203] opened 2020-03-02 17:24 UTC
```
Application started. Press Ctrl+C to shut down.
fail: Zigbee2MqttAssistant.Services.MqttConnectionService[0]
      Error processing MQTT message on topic 'zigbee2mqtt/bridge/ota_update/update'
Newtonsoft.Json.JsonReaderException: Unexpected character encountered while parsing value: Z. Path '', line 0, position 0.
   at Newtonsoft.Json.JsonTextReader.ParseValue()
   at Newtonsoft.Json.Linq.JObject.Load(JsonReader reader, JsonLoadSettings settings)
   at Newtonsoft.Json.Linq.JObject.Parse(String json, JsonLoadSettings settings)
   at Zigbee2MqttAssistant.Services.BridgeStateService.UpdateDevice(String friendlyName, String jsonPayload, Boolean& forceLastSeen) in d:\a\1\s\Zigbee2MqttAssistant\Services\BridgeStateService.cs:line 144
   at Zigbee2MqttAssistant.Services.MqttConnectionService.DispatchZigbee2MqttMessage(MqttApplicationMessage msg) in d:\a\1\s\Zigbee2MqttAssistant\Services\MqttConnectionService.cs:line 493
   at Zigbee2MqttAssistant.Services.MqttConnectionService.HandleApplicationMessageReceivedAsync(MqttApplicationMessageReceivedEventArgs eventArgs) in d:\a\1\s\Zigbee2MqttAssistant\Services\MqttConnectionService.cs:line 400
```

**Comment by magpern** [comment] 2020-03-02 22:33
@carldebilly do you have any other info? What did you do? What could have caused this? I have tried several times and I do not get any errors.

**Comment by carldebilly** [comment] 2020-03-03 18:45
It seems to occurs when the upgrade command is sent from Z2MA...

**Comment by magpern** [comment] 2020-03-07 23:53
Duplicate of #109

**Comment by magpern** [comment] 2020-03-08 23:59
Problem is in UpdateDevice. This function requires a JSON string, but very often get stray messages that are just strings. These cannot (and should not) be parsed. Simply ignored.

Similar issue in #225 and #109

**Closed** 2020-03-09 13:45 UTC
Labels: bug

**Comment by carldebilly** [comment] 2020-03-10 13:49
Thanks @magpern for your involvement in this project!
