### ISSUE TITLE
Unable to delete old devices

### ISSUE THREAD

**Issue by podkilla** [yllibed/Zigbee2MqttAssistant#43] opened 2019-09-24 00:22 UTC
HA: 0.99.2
Zigbee2Mqtt: 1.6.0
zigbee2mqttassistant: 0.2.0-dev.76

It is not possible for me to remove devices i had once used before but are now in another mesh network on a different controller (conbee II)

When removing these old devices i get the following message in the log:

`Unable to qualify a message received on topic 'zigbee2mqtt/bridge/config/remove'`

The device then is gone but only until i restart the Zigbee2MqttAssistant. Then everything is back as before.

**Comment by carldebilly** [comment] 2019-09-24 13:39
The warning is misleading : it's just to let know it can't do anything with this message, but that's correct.

It's a duplicate of #29, so I'll close this bug.

**Closed by carldebilly** 2019-09-24 13:39 UTC

**Comment by carldebilly** [comment] 2019-09-25 04:40
The warning is fixed in latest version `0.2.0-dev.94`!

Please test it and come back if there's any problem remaining.
