### ISSUE TITLE
Explantion of tags - Zigbee2Mqtt "offline" unreliable

### ISSUE THREAD

**Issue by james-fry** [yllibed/Zigbee2MqttAssistant#15] opened 2019-08-24 22:01 UTC
I have seen a few odd or inconsistent tags against devices.
Not sure if this is coming from Zigbee2Mqtt itself from the scan data, or from Zigbee2MqttAssistant...

1) Offline device (bulb that is physically disconnected from power) shows as "very weak link" rather than offline.

![image](https://user-images.githubusercontent.com/5823294/63643127-21879700-c6c2-11e9-83ce-59cfa5a306e7.png)

![image](https://user-images.githubusercontent.com/5823294/63643134-3106e000-c6c2-11e9-9616-a9bc0997b3b4.png)

BTW this device is correctly not in the graphml map diagram since its not in the network.
It is in the DB so correctly listed by Zigbee2MqttAssistant

2) All routers are tagged as "offline".
I think this one is Zigbee2Mqtt since I also see in the graphml diagram.

![image](https://user-images.githubusercontent.com/5823294/63643155-6ad7e680-c6c2-11e9-98a8-006d72032d9d.png)

![image](https://user-images.githubusercontent.com/5823294/63643159-8642f180-c6c2-11e9-8d3d-e6d6d04a4bab.png)

WDYT on these?

**Comment by carldebilly** [comment] 2019-08-25 15:33
Zigbee2MqttAssistant is just presenting information coming from Zigbee2Mqtt.  I have the same problem at home were perfectly working devices are tagged as offline.

I think we should ask @Koenkk to explain it to us.

**Comment by Koenkk** [comment] 2019-08-26 06:07
This state is not reliable: https://github.com/Koenkk/zigbee-herdsman/issues/13

I would recommend hiding it for now

**Comment by james-fry** [comment] 2019-08-26 13:24
Thanks @carldebilly @Koenkk 
I will ignore it for now - in all locations/UIs
@carldebilly up to you if you hide it or leave it...

**Comment by francisp2** [comment] 2019-08-27 17:08
Same here. All my devices are offline until I 'reset local state'

**Comment by carldebilly** [comment] 2019-08-29 14:55
@Koenkk What do you suggest? To rely only on _last_seen_ information?

**Comment by Koenkk** [comment] 2019-08-30 08:49
@carldebilly `last_seen` is reliable, please create an issue then I will add it after https://github.com/koenkk/zigbee2mqtt/issues/1888

**Comment by carldebilly** [comment] 2019-10-10 03:14
#71 is closing this bug.  It's not a bug anymore: the _offline_ feature will be removed from Z2M.

**Closed by carldebilly** 2019-10-10 03:14 UTC
Labels: bug
